spring:
  application:
    name: api
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: get_cats_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/cats/**